### ISSUE TITLE
Issues on weird result & High VRAM usage

### ISSUE THREAD

**Issue by jeolpyeoni** [damo-cv/RealisDance#17]
Hello, thank you for the great, impressive work!
I tried to follow the instructions for running the demo, but I encountered several issues:

1. The model was producing erroneous results. While the model seems to take at minimum of 16 frames video, but providing the video with a small number of frames (even for about 32 frames video) produced erroneous results with visual artifacts.

Here is the example of such results, when providing 16 frames video as input.
https://github.com/user-attachments/assets/c69f12a4-87e2-49bd-b579-a952419bd044

2. The VRAM usage was too high, where it was even hard for generating 80 frames video with A6000 48G GPU, different from what it's mentioned in other issue.

**Comment by jeolpyeoni** [comment]
Regarding the first issue, I figured out that the model works appropriately when providing the videos with more than 64 frames length.

However, the model seems to be trained with 16 frames length videos, thus I assume it should work properly with those videos. It would be great if this is clarified.

**Comment by yuchenli-sony** [comment]
bro, you are so handsome

**Comment by theFoxofSky** [comment]
Thanks for reporting this issue. This seems to be caused by a bug in the inference pipeline, let me check it out.

**Comment by theFoxofSky** [comment]
I checked everything but I can't reproduce this issue.

How do you achieve 16-frame inference? I guess this issue may be caused by the wrong window splitting.
Please pay attention to the window-splitting code in the pipeline (L374-376).
`
  context_queue = list(context_scheduler(
    i, num_inference_steps, latents.shape[2], context_frames, context_stride, context_overlap,
))
`
Make sure that latetns.shape[2] == pose.shape[2] == context_frames == 16

**Comment by jeolpyeoni** [comment]
I just provided the video with the length of 16 frames as input.
I'll check it again, and tell you what happens
Many thanks!

**Comment by theFoxofSky** [comment]
> I just provided the video with the length of 16 frames as input. I'll check it again, and tell you what happens Many thanks!

Oh! Reading a video with only 16 frames will result in 4 frames, because 'simple reader' performs 4-frame stride during video reading.

Please check the function 'simple reader' in inference.py (L39-98)

**Comment by theFoxofSky** [comment]
You can fix this by modifying the stride in inference.py (L72)

**Comment by jeolpyeoni** [comment]
Oh, now I got the sense.
Many thanks for your kind explanation!
