### ISSUE TITLE
FileNotFoundError: file "../../../../_base_/datasets/coco.py" does not exist

### ISSUE THREAD

**Issue by huiyang865** [damo-cv/RealisDance#26]
coco.py not in the prepare_pose\smplerX\main\_base_ directory, causing running error.

**Comment by theFoxofSky** [comment]
Please check this @Wangbenzhi

**Comment by yuananf** [comment]
Same here

**Comment by HW140701** [comment]
Copy the dataset folder under this path from the original smplerx repository to this repository, and under the dataset folder there is coco.py
