### ISSUE TITLE
missing keys and unmatched keys in loading unet model

### ISSUE THREAD

**Issue by test-dddjjj** [damo-cv/RealisDance#35]
Hello:

I have encountered this error during inference while loading unet models: 
![image](https://github.com/user-attachments/assets/c7531ffd-d6be-4ece-977a-c577098fb095)
 

it can infer but has shown this error. It will be much appreciated if you reply. Thanks.

**Comment by theFoxofSky** [comment]
This is just a warning as, we first init a Unet3D use rv-5-1, then load the weight from the ckpt

**Comment by test-dddjjj** [comment]
> This is just a warning, as we first init a Unet3D use rv-5-1, then load the weight from the ckpt

okk, thank you for your explaination.
