### ISSUE TITLE
Have you ever tried using a model with better quality model ` animatediff sdxl` for training?

### ISSUE THREAD

**Issue by wangqiang9** [damo-cv/RealisDance#46]
Hi, thank you for your outstanding work.

I noticed that you are training based on `animatediff v2`. Have you tried using a model with better quality model animatediff sdxl for training? Will replacing with animatediff sdxl improve the generation quality? 

Thank you!

**Comment by theFoxofSky** [comment]
No more animate-diff, CogVideoX or Mochi will be your next choice
