### ISSUE TITLE
unable to run hamer

### ISSUE THREAD

**Issue by LongVu219** [damo-cv/RealisDance#47]
when i tried to run hamer inference : python inference_video.py --video_path {YOUR_VIDEO_PATH} --output_path {OUTPUT_PATH} i got the error : ImportError: ('Unable to load OpenGL library', "/data/duongnv/miniconda3/envs/hamer/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-17.so.1)", 'libOSMesa.so.8', 'libOSMesa.so.8') 
Then i try to fix this by running : apt-get install -y python-opengl libosmesa6 but i now get the error : E: Unable to locate package python-opengl
I have done and complete all the step in hamer repo. Please tell me how can i fix this ? @theFoxofSky

**Comment by theFoxofSky** [comment]
@Wangbenzhi

**Comment by LongVu219** [comment]
> @Wangbenzhi

after a lot of debugging now i got error : ImportError: cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa' (/home/duongnv/miniconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/osmesa/__init__.py)
after running : apt-get install -y python-opengl libosmesa6 i still get the above error
please help @Wangbenzhi

**Comment by Wangbenzhi** [comment]
it seems a common issue, maybe you can try https://github.com/huggingface/deep-rl-class/issues/275

**Comment by LongVu219** [comment]
> it seems a common issue, maybe you can try [huggingface/deep-rl-class#275](https://github.com/huggingface/deep-rl-class/issues/275)

thank you so much for your help, i have fixed my issue according to this post, but there is no hamer.datasets in your repo, i have found that it's available in the origin HaMer repo, maybe some copy-paste error ?
