### ISSUE TITLE
Pretrained Checkpoint Issue

### ISSUE THREAD

**Issue by Hasan0ff** [damo-cv/RealisDance#5]
`# prepare rv-5-1
mkdir RV
cd RV
ln -s $PATH-TO-RV-5-1 rv-5-1
cd ../

# prepare dino v2
mkdir DINO
cd DINO
ln -s $PATH-TO-DINOV2 dinov2
cd ../

# prepare motion module
mkdir MM
cd MM
ln -s $PATH-TO-MM mm_v2.ckpt
cd ../

(Optional)
# prepare sd-vae-ft-mse
# link to a SD dir with a subfolder named 'sd-vae-ft-mse' `

except sd-vae-ft-mse the rest are problematic to download as there is a problem with the folders. Authors haven't shown how should we use the folder structure. I tried yesterday to check the quality. The installation was fine and easy. However, rv-5-1 I assume is SD 1.5. I downloaded from huggingface and added the link. but when i tried to run it said that the folder structure has to be like StableDiffusion/v15 or something like that. At least, authors should tell us which model to use and how to structure the folders.

then dinov2 has 3 or so models. It has base model, giant model and huge model. Which one should be used? 

as for motion module, still the same problem. Which motion module and how to structure the folders.

thanks a lot and good luck.

**Comment by theFoxofSky** [comment]
Sorry, the VAE preparation is not clear enough. I use the sd-vae-ft-mse (https://huggingface.co/stabilityai/sd-vae-ft-mse) as the default setting, but I mentioned it as the optional component in the readme. I will modify the config to fix it.

**Comment by Hasan0ff** [comment]
it's all good mate. Please give reference to rv-5-1, dinov2 and mm_v2.ckpt too. It's almost impossible to find them unless you already know in advance which models and .pth files they refer to.

**Comment by Hasan0ff** [comment]
by the way, how many GB of GPU is needed for inference and for training? I am using A100, I wonder if its enough for training?

**Comment by theFoxofSky** [comment]
Sure, 
RV-5-1: https://huggingface.co/SG161222/Realistic_Vision_V5.1_noVAE
DINOV2-L: https://huggingface.co/facebook/dinov2-large/tree/main
mm_v2: https://github.com/guoyww/AnimateDiff

A100 is enough.
I will modify the readme. Thanks

**Comment by theFoxofSky** [comment]
I also modified the configs so that you no longer need sd-vae-ft-mse by default.

**Comment by Hasan0ff** [comment]
thanks for the hard work!

**Comment by theFoxofSky** [comment]
For inference, it is related to the sequence length. Normally, for a sequence with 80 frames, A10 with 24G is enough.

**Comment by Hasan0ff** [comment]
thanks mate

**Comment by matbee-eth** [comment]
Which mm_v2? `[mm_sd_v15_v2.ckpt](https://huggingface.co/guoyww/animatediff/blob/main/mm_sd_v15_v2.ckpt)?

**Comment by xiezheng-cs** [comment]
> For inference, it is related to the sequence length. Normally, for a sequence with 80 frames, A10 with 24G is enough.
Why does CUDA out of memory occur in V100  32G？
@theFoxofSky

**Comment by theFoxofSky** [comment]
> > For inference, it is related to the sequence length. Normally, for a sequence with 80 frames, A10 with 24G is enough.
> > Why does CUDA out of memory occur in V100  32G？
> > @theFoxofSky

It depends on your resolution and sequence length, we have tested RealisDance on both A10, L20, and H20.  In our devices, 24G is enough.

Just tested again a few minutes ago on H20 using the demo sequence.
![image](https://github.com/user-attachments/assets/a4f186d5-254e-46de-afaf-c950b10edb1a)

**Comment by xiezheng-cs** [comment]
parser.add_argument("--H", type=int, default=768)
    parser.add_argument("--W", type=int, default=576)
    parser.add_argument("--cH", type=int, default=320)
    parser.add_argument("--cW", type=int, default=240)
    parser.add_argument("--max-L", type=int, default=80)
    
default resolution and sequence length? @theFoxofSky

**Comment by theFoxofSky** [comment]
> ```
> parser.add_argument("--H", type=int, default=768)
> parser.add_argument("--W", type=int, default=576)
> parser.add_argument("--cH", type=int, default=320)
> parser.add_argument("--cW", type=int, default=240)
> parser.add_argument("--max-L", type=int, default=80)
> ```
> 
> default resolution and sequence length? @theFoxofSky

Yes
